version: '3.8'
services:
  postgres:
    container_name: driverGO_db
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=driverGO
    ports:
      - "4000:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: