---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml


volumes:
  grafana: