// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/log/logger.go

// Package mock_log is a generated GoMock package.
package mock_log

import (
	reflect "reflect"

	log "github.com/MaksKazantsev/DriverGO/internal/log"
	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, data *log.Data) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg, data)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), msg, data)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, data *log.Data) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg, data)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), msg, data)
}

// Trace mocks base method.
func (m *MockLogger) Trace(key, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Trace", key, msg)
}

// Trace indicates an expected call of Trace.
func (mr *MockLoggerMockRecorder) Trace(key, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trace", reflect.TypeOf((*MockLogger)(nil).Trace), key, msg)
}
